version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - gdse

    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - gdse

    node:
        build: .docker/node
        container_name: node
        restart: always
        ports:
            - "3000:3000"
            - "35729:35729"
        volumes:
            - ./node_modules:/var/www/node_modules
            - .:/var/www
        networks:
            - gdse

    postgres:
        image: postgis/postgis:15-3.3-alpine
        volumes:
            - ./.docker/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: gisdb
            PGDATA: /var/lib/postgresql/data
        networks:
            - gdse
            
    geoserver:
        image: kartoza/geoserver:latest
        ports:
            - "8081:8080"
        volumes:
            - ./.docker/geoserver:/opt/geoserver/data_dir
        environment:
            GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
            GEOSERVER_ADMIN_USER: admin
            GEOSERVER_ADMIN_PASSWORD: geoserver
        networks:
            - gdse

networks:
    gdse:

volumes:
    .docker:
